name: Build and Publish image

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: test-image
  IMAGE_TAG: bookworm

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::863419159770:role/DockerTestImageGithubActionsAccessRole
        aws-region: eu-north-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        provenance: false
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
